apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
  template:
    metadata:
      labels:
        app: watchtower
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: watchtower
        image: docker.io/mdiggin/yass-watchtower:0.1
        command: ["./watchtower"]
        args: ["-f", "/wt/node_data"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8010
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          exec:
            command: ["./grpc_health_probe", "-addr=:8010"]
          initialDelaySeconds: 10
        volumeMounts:
          - mountPath: /wt
            name: wt-volume
      volumes:
        - emptyDir: {}
          name: wt-volume