// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/michael-diggin/yass/gateway/api (interfaces: GrpcClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	models "github.com/michael-diggin/yass/models"
	reflect "reflect"
)

// MockGrpcClient is a mock of GrpcClient interface
type MockGrpcClient struct {
	ctrl     *gomock.Controller
	recorder *MockGrpcClientMockRecorder
}

// MockGrpcClientMockRecorder is the mock recorder for MockGrpcClient
type MockGrpcClientMockRecorder struct {
	mock *MockGrpcClient
}

// NewMockGrpcClient creates a new mock instance
func NewMockGrpcClient(ctrl *gomock.Controller) *MockGrpcClient {
	mock := &MockGrpcClient{ctrl: ctrl}
	mock.recorder = &MockGrpcClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGrpcClient) EXPECT() *MockGrpcClientMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method
func (m *MockGrpcClient) BatchDelete(arg0 context.Context, arg1 int, arg2, arg3 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete
func (mr *MockGrpcClientMockRecorder) BatchDelete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockGrpcClient)(nil).BatchDelete), arg0, arg1, arg2, arg3)
}

// BatchSend mocks base method
func (m *MockGrpcClient) BatchSend(arg0 context.Context, arg1, arg2 int, arg3 string, arg4, arg5 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSend", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSend indicates an expected call of BatchSend
func (mr *MockGrpcClientMockRecorder) BatchSend(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSend", reflect.TypeOf((*MockGrpcClient)(nil).BatchSend), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Check mocks base method
func (m *MockGrpcClient) Check(arg0 context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check
func (mr *MockGrpcClientMockRecorder) Check(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGrpcClient)(nil).Check), arg0)
}

// Close mocks base method
func (m *MockGrpcClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockGrpcClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGrpcClient)(nil).Close))
}

// DelValue mocks base method
func (m *MockGrpcClient) DelValue(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelValue indicates an expected call of DelValue
func (mr *MockGrpcClientMockRecorder) DelValue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelValue", reflect.TypeOf((*MockGrpcClient)(nil).DelValue), arg0, arg1, arg2)
}

// GetValue mocks base method
func (m *MockGrpcClient) GetValue(arg0 context.Context, arg1 string, arg2 int) (*models.Pair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Pair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue
func (mr *MockGrpcClientMockRecorder) GetValue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockGrpcClient)(nil).GetValue), arg0, arg1, arg2)
}

// SetValue mocks base method
func (m *MockGrpcClient) SetValue(arg0 context.Context, arg1 *models.Pair, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValue indicates an expected call of SetValue
func (mr *MockGrpcClientMockRecorder) SetValue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValue", reflect.TypeOf((*MockGrpcClient)(nil).SetValue), arg0, arg1, arg2)
}
