kind: Service
apiVersion: v1
metadata:
# This service exists so the pods in the stateful state have DNS entries
# So that they can reach each other
  name: server-internal
spec:
  selector:
    app: yass
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  ClusterIP: None