apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yass-server
spec:
  serviceName: "yassdb"
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: yass
  template:
    metadata:
      labels:
        app: yass
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: yass
        image: docker.io/mdiggin/yass-server:0.1
        imagePullPolicy: IfNotPresent
        command: ["./server"]
        args: ["-g", "watchtower:80", "-p", "8080"]
        ports:
        - containerPort: 8080
        env:
        - name: pod_name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAME
          value: "$(pod_name).yassdb:8080"
        livenessProbe:
          exec:
            command: ["./grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 256Mi 